### ISSUE TITLE
d3 examples - new folder?

### ISSUE THREAD

**Issue by jwilber** [ml5js/ml5-examples#178]
Hey all,

I just wrote a kmeans class for ml5-library I'll PR shortly. I have an example that uses d3 (interactive cluster assignments for different datasets) - should I create a new directory called `/d3` in the PR here? Or should I just throw the example in the existing `/javascript` dir?

Thanks!

**Comment by joeyklee** [comment]
Hi @jwilber - Wow! Super cool. Thanks so much. 
In this instance since there is a dependency to `d3`, I would go ahead and add a `/d3` directory for now so we can have a look. 

@shiffman usually keeps an eye on keeping examples as simple as possible as well as supporting all examples in `p5`, so we might also create a `p5` port of your d3 example at some point. 

I hope this helps! Thanks + looking forward!

**Comment by joeyklee** [comment]
Closing this now. Thanks so much @jwilber !

**Comment by jwilber** [comment]
Great, thanks so much for all the help @joeyklee!
Should I open another PR for a pure P5js example? (Somewhere I have one where you upload an image, and it finds the color palette using KMeans on the pixels), or is the pure D3 fine?
Stoked to contribute in any case!

**Comment by joeyklee** [comment]
@jwilber - Thanks so much for all the hard work! It's great to see this all part of the lib. I'm definitely curious to see what kinds of creative uses people come up with. 

If you'd like to submit a p5 example that'd be great! I'd love to see it. One thing we'd love to highlight are those kinds of creative use cases.
